#ifndef KONGKONG_WIN32_DIRECTX_H
#define KONGKONG_WIN32_DIRECTX_H

#include "Definitions/Base.h"

//Windowsのみ
#if KONGKONG_ENV_WINDOWS

#endif //KONGKONG_ENV_WINDOWS
#endif //!KONGKONG_WIN32_DIRECTX_H
