#ifndef KONGKONG_APPLEDEVICE_FOUNDATION_TEXT_H
#define KONGKONG_APPLEDEVICE_FOUNDATION_TEXT_H

#include "Definitions/Base.h"

#if KONGKONG_OBJECTIVE_C_ENABLED

#include "Definitions/Kongkong.AppleDevice.Foundation.Text.NSScanner.h"

#endif //KONGKONG_OBJECTIVE_C_ENABLED

#endif //!KONGKONG_APPLEDEVICE_FOUNDATION_TEXT_H
