#ifndef KONGKONG_APPLEDEVICE_FOUNDATION_FILESYSTEM_H
#define KONGKONG_APPLEDEVICE_FOUNDATION_FILESYSTEM_H

#ifdef KONGKONG_OBJECTIVE_C_ENABLED

#include "Definitions/Base.h"
#include "Definitions/Kongkong.AppleDevice.Foundation.FileSystem.NSFileManager.h"

#endif //KONGKONG_OBJECTIVE_C_ENABLED

#endif //!KONGKONG_APPLEDEVICE_FOUNDATION_FILESYSTEM_H
