#ifndef KONGKONG_APPLEDEVICE_FOUNDATION_THREADING_NSTHREADCREATE_H
#define KONGKONG_APPLEDEVICE_FOUNDATION_THREADING_NSTHREADCREATE_H

#include "Base.h"

namespace KONGKONG_NAMESPACE::Posix::Threading
{
    enum struct ThreadCreate {
        Joinable = PTHREAD_CREATE_JOINABLE,
        Detached = PTHREAD_CREATE_DETACHED,
    };
}

#endif //!KONGKONG_APPLEDEVICE_FOUNDATION_THREADING_NSTHREADCREATE_H
