#ifndef KONGKONG_WIN32_UI_WINDOWCORNERPREFERENCE_H
#define KONGKONG_WIN32_UI_WINDOWCORNERPREFERENCE_H

#include "Base.h"

namespace KONGKONG_NAMESPACE::Win32::UI
{
    //Windows11の角丸設定
    enum struct WindowCornerPreference {
        Default    = DWM_WINDOW_CORNER_PREFERENCE::DWMWCP_DEFAULT,
        DoNotRound = DWM_WINDOW_CORNER_PREFERENCE::DWMWCP_DONOTROUND,
        Round      = DWM_WINDOW_CORNER_PREFERENCE::DWMWCP_ROUND,
        RoundSmall = DWM_WINDOW_CORNER_PREFERENCE::DWMWCP_ROUNDSMALL,
    };
}

#endif //!KONGKONG_WIN32_UI_WINDOWCORNERPREFERENCE_H
