#ifndef KONGKONG_WIN32_SOUNDKIND_H
#define KONGKONG_WIN32_SOUNDKIND_H

#include "Base.h"

namespace KONGKONG_NAMESPACE::Win32
{
    enum struct SoundKind {
        AppGPFault,
        CCSelect,
        ChangeTheme,
        Close,
        CriticalBatteryAlarm,
        Default,
        DeviceConnect,
        DeviceDisconnect,
        DeviceFail,
        FaxBeep,
        LowBatteryAlarm,
        MailBeep,
        Maximize,
        MenuCommand,
        MenuPopup,
        Minimize,
        MessageNudge,
        NotificationDefault,
        NotificationIM,
        NotificationLoopingAlarm,
        NotificationLoopingAlarm2,
        NotificationLoopingAlarm3,
        NotificationLoopingAlarm4,
        NotificationLoopingAlarm5,
        NotificationLoopingAlarm6,
        NotificationLoopingAlarm7,
        NotificationLoopingAlarm8,
        NotificationLoopingAlarm9,
        NotificationLoopingAlarm10,
        NotificationLoopingCall,
        NotificationLoopingCall2,
        NotificationLoopingCall3,
        NotificationLoopingCall4,
        NotificationLoopingCall5,
        NotificationLoopingCall6,
        NotificationLoopingCall7,
        NotificationLoopingCall8,
        NotificationLoopingCall9,
        NotificationLoopingCall10,
        NotificationMail,
        NotificationProximity,
        NotificationReminder,
        NotificationSMS,
        Open,
        PrintComplete,
        ProximityConnection,
        RestoreDown,
        RestoreUp,
        ShowBand,
        SystemAsterisk,
        SystemExit,
        SystemExclamation,
        SystemHand,
        SystemNotification,
        SystemQuestion,
        SystemStart,
        WindowsLogoff,
        WindowsLogon,
        WindowsUAC,
        WindowsUnlock,
    };
}

#endif //!KONGKONG_WIN32_SOUNDKIND_H
