#ifndef KONGKONG_WIN32_PROCESSORARCHITECTURE_H
#define KONGKONG_WIN32_PROCESSORARCHITECTURE_H

#include "Base.h"

namespace KONGKONG_NAMESPACE::Win32
{
    enum struct ProcessorArchitecture : uint16_t {
        X86          = PROCESSOR_ARCHITECTURE_INTEL,
        ARM32        = PROCESSOR_ARCHITECTURE_ARM,
        IntelItanium = PROCESSOR_ARCHITECTURE_IA64,
        X64          = PROCESSOR_ARCHITECTURE_AMD64,
        ARM64        = PROCESSOR_ARCHITECTURE_ARM64,
        Unknown      = PROCESSOR_ARCHITECTURE_UNKNOWN,
    };
}

#endif //!KONGKONG_WIN32_PROCESSORARCHITECTURE_H
